APP_REVIEW_PAGES = 10
MANUAL_REVIEW_PAGES = 2
GAME_CATEGORY_ID = 20
SCIENCE_TECH_ID = 28
HOW_TO_STYLE_ID = 26

YOUTUBE_COMMENTS_AMOUNT = 100
YOUTUBE_VIDEO_AMOUNT = 5

APPLE_GAMES_GENRE_ID = 6014
APPLE_SOCIAL_GENRE_ID = 6005
APPLE_UTILITIES_GENRE_ID = 6002
APPLE_TOP_APPS_LIMIT = 5
APPLE_COUNTRY = "us"

RAG_TOP_K = 5
RAG_MIN_SIMILARITY = 0.35
RAG_COLLECTION = "insights"