APP_REVIEW_PAGES = 10
GAME_CATEGORY_ID = 20
SCIENCE_TECH_ID = 28
HOW_TO_STYLE_ID = 26

YOUTUBE_COMMENTS_AMOUNT = 100
YOUTUBE_VIDEO_AMOUNT = 5

APPLE_GAMES_GENRE_ID = 6014
APPLE_SOCIAL_GENRE_ID = 6005
APPLE_TOP_APPS_LIMIT = 5
APPLE_COUNTRY = "us"